export const reactions = [
  { emoji: '❤️', label: 'LOVE' },
  { emoji: '😃', label: 'HAPPY' },
  { emoji: '😮', label: 'WOW' },
  { emoji: '😢', label: 'SAD' },
  { emoji: '😐', label: 'MEH' },
  { emoji: '😡', label: 'ANGRY' },
  { emoji: '👍', label: 'LIKE' },
  { emoji: '👎', label: 'DISLIKE' },
  { emoji: '🌶️', label: 'SPICY' },
  { emoji: '🍬', label: 'SWEET' },
  { emoji: '🍪', label: 'CRUNCHY' },
  { emoji: '🧂', label: 'TOO_SALTY' },
  { emoji: '🍭', label: 'TOO_SWEET' },
];
