import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the type for the auth state
type AuthState = {
  isAuthenticated: boolean;
  user: any | null; // Replace 'any' with your actual user interface/type if you have one
};

// Set the initial state with an explicit type
const initialState: AuthState = {
  isAuthenticated: false,
  user: null,
};

// Create a slice for authentication state
const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    // Action for login success
    loginSuccess: (state, action: PayloadAction<any>) => {
      state.isAuthenticated = true;
      state.user = action.payload; // Store user data on successful login
    },
    // Action for logout
    logout: (state) => {
      state.isAuthenticated = false;
      state.user = null; // Clear user data on logout
    },
  },
});

// Export the actions generated by createSlice
export const { loginSuccess, logout } = authSlice.actions;

// Export the reducer to be included in the Redux store
export default authSlice.reducer;
