
export const categories = [
{
  name: 'Electronics & Appliances',
  description: 'Explore a wide range of electronic devices and home appliances, from smartphones to smart home systems.',
  subcategories: [
    { name: 'Mobile Phones', description: 'Smartphones and mobile devices for communication and entertainment.' },
    { name: 'Computers & Laptops', description: 'Desktops, laptops, and accessories for work and play.' },
    { name: 'Tablets & Accessories', description: 'Tablets and related accessories for versatile computing.' },
    { name: 'Cameras & Photography', description: 'Digital cameras, lenses, and photography equipment.' },
    { name: 'Home Appliances', description: 'Essential appliances for everyday household tasks.' },
    { name: 'Audio & Sound Systems', description: 'Speakers, headphones, and audio equipment for all purposes.' },
    { name: 'Wearable Technology', description: 'Smartwatches, fitness trackers, and other wearable devices.' },
    { name: 'Smart Home Devices', description: 'Automation devices for modern, smart home living.' },
  ],
},
{
  name: 'Fashion & Apparel',
  description: 'Stylish and trendy clothing and accessories for men, women, and children, including jewelry and watches.',
  subcategories: [
    { name: 'Men’s Clothing', description: 'Stylish and comfortable clothing for men.' },
    { name: 'Women’s Clothing', description: 'Elegant and trendy clothing for women.' },
    { name: 'Kids’ Clothing', description: 'Fashionable and durable clothing for children.' },
    { name: 'Shoes', description: 'Footwear for all occasions and styles.' },
    { name: 'Accessories', description: 'Belts, hats, bags, and other fashion accessories.' },
    { name: 'Jewelry', description: 'Necklaces, rings, and more for personal adornment.' },
    { name: 'Watches', description: 'Wristwatches and smartwatches for style and utility.' },
  ],
},
{
  name: 'Health & Wellness',
  description: 'Health, beauty, personal care, and medical supplies to support a healthy lifestyle.',
  subcategories: [
    { name: 'Skincare', description: 'Products to nourish and protect your skin.' },
    { name: 'Haircare', description: 'Shampoos, conditioners, and styling products.' },
    { name: 'Makeup & Cosmetics', description: 'Beauty products to enhance your features.' },
    { name: 'Personal Care', description: 'Everyday hygiene products for personal care.' },
    { name: 'Health Supplements', description: 'Vitamins and supplements for better health.' },
    { name: 'Medical Equipment', description: 'Essential equipment for healthcare needs.' },
    { name: 'Fitness & Wellness', description: 'Tools and gear for maintaining physical fitness.' },
  ],
},
{
  name: 'Home & Living',
  description: 'Enhance your living spaces with quality furniture, decor, and household essentials.',
  subcategories: [
    { name: 'Furniture', description: 'Stylish and functional furniture for every room.' },
    { name: 'Home Decor', description: 'Decorative items to beautify your home.' },
    { name: 'Kitchen & Dining', description: 'Cookware, utensils, and dining essentials.' },
    { name: 'Bedding & Bath', description: 'Comfortable and luxurious bedding and bath items.' },
    { name: 'Lighting', description: 'Modern and decorative lighting solutions.' },
    { name: 'Storage Solutions', description: 'Organizational tools to maximize space.' },
    { name: 'Garden & Outdoor', description: 'Equipment and decor for outdoor living.' },
  ],
},
{
  name: 'Food & Beverages',
  description: 'A diverse selection of food and beverages, including fresh produce, meats, seafood, packaged and frozen foods, snacks, and drinks.',
  subcategories: [
    { name: 'Fresh Produce', description: 'Fresh fruits, vegetables, and herbs, including eggs.' },
    { name: 'Packaged Foods', description: 'Convenient and ready-to-eat packaged foods.' },
    { name: 'Frozen Foods', description: 'Frozen meals and ingredients for quick preparation.' },
    { name: 'Beverages', description: 'Soft drinks, juices, and alcoholic beverages.' },
    { name: 'Snacks & Confectionery', description: 'Sweet and savory snacks for every occasion.' },
    { name: 'Meats & Poultry', description: 'Fresh and frozen meats like chicken, beef, and pork.' },
    { name: 'Seafood', description: 'Fresh and frozen fish, shellfish, and other seafood.' },
  ],
},
{
  name: 'Dining & Restaurants',
  description: 'Explore a variety of dining options, from quick service to fine dining, catering to all tastes and occasions.',
  subcategories: [
    { name: 'Fast Food & Quick Service', description: 'Quick and convenient meal options for busy lifestyles.' },
    { name: 'Casual Dining', description: 'Relaxed dining environments offering a variety of cuisines.' },
    { name: 'Fine Dining', description: 'Luxurious dining experiences with gourmet dishes and premium service.' },
    { name: 'Cafes & Bakeries', description: 'Cozy spaces serving coffee, pastries, and light meals.' },
    { name: 'Catering Services', description: 'Customized catering solutions for events and special occasions.' },
  ],
},
{
  name: 'Books & Stationery',
  description: 'Books for every reader and a wide selection of stationery for school or office needs.',
  subcategories: [
    { name: 'Fiction & Non-fiction Books', description: 'Books spanning a variety of genres and interests.' },
    { name: 'School Supplies', description: 'Essentials for students and teachers alike.' },
    { name: 'Art Supplies', description: 'Paints, brushes, and tools for creative expression.' },
    { name: 'Notebooks & Journals', description: 'Stationery for writing, sketching, or journaling.' },
    { name: 'Office Supplies', description: 'Products to keep your workspace organized and efficient.' },
  ],
},
{
  name: 'Sports & Outdoor',
  description: 'Gear and apparel for fitness, sports, and outdoor adventures.',
  subcategories: [
    { name: 'Exercise & Fitness Equipment', description: 'Tools for strength training, cardio, and yoga.' },
    { name: 'Camping & Hiking Gear', description: 'Essentials for exploring the great outdoors.' },
    { name: 'Sports Apparel', description: 'Clothing designed for active lifestyles.' },
    { name: 'Bicycles & Accessories', description: 'Bikes and equipment for cycling enthusiasts.' },
    { name: 'Fishing Gear', description: 'Rods, reels, and supplies for anglers.' },
    { name: 'Water Sports Gear', description: 'Equipment for swimming, surfing, and water-based activities.' },
  ],
},
{
  name: 'Automotive & Motorcycles',
  description: 'Products for car and motorcycle enthusiasts, including accessories and maintenance tools.',
  subcategories: [
    { name: 'Car Accessories', description: 'Accessories to enhance your car\'s comfort and style.' },
    { name: 'Motorcycle Accessories', description: 'Gear and tools for motorcycle maintenance and upgrades.' },
    { name: 'Car Care & Maintenance', description: 'Cleaning products and tools to maintain your vehicle.' },
    { name: 'Tires & Wheels', description: 'Durable tires and stylish wheel options.' },
    { name: 'Car Electronics', description: 'Audio systems, GPS, and other car electronics.' },
  ],
},
{
  name: 'Real Estate & Rentals',
  description: 'Explore properties for sale or rent, including residential, commercial, and vacation rentals.',
  subcategories: [
    { name: 'Residential Properties', description: 'Homes, apartments, and condos for sale or rent.' },
    { name: 'Commercial Properties', description: 'Office spaces, retail stores, and warehouses for sale or lease.' },
    { name: 'Vacation Rentals', description: 'Short-term rentals for vacations or holidays.' },
    { name: 'Land & Lots', description: 'Vacant land and plots for sale or lease.' },
    { name: 'Shared Rentals', description: 'Rooms or shared living spaces available for rent.' },
    { name: 'Specialty Properties', description: 'Farmhouses, resorts, and other unique property types.' },
  ],
},
{
  name: 'Digital Downloads',
  description: 'A variety of digital products that can be instantly downloaded, from software to creative assets.',
  subcategories: [
    { name: 'E-books & Audiobooks', description: 'Digital books and audiobooks for instant reading or listening.' },
    { name: 'Software & Applications', description: 'Productivity tools, antivirus, and other downloadable software.' },
    { name: 'Digital Art & Illustrations', description: 'Artwork, illustrations, and templates for creative projects.' },
    { name: 'Music & Sound Effects', description: 'Audio tracks and sound effects for media production or entertainment.' },
    { name: 'Photos & Stock Images', description: 'High-quality images and stock photos for personal or commercial use.' },
    { name: 'Templates & Themes', description: 'Web, graphic, and document templates for creative or business use.' },
    { name: 'Courses & Tutorials', description: 'Online courses and educational materials for skill development.' },
    { name: '3D Models & CAD Files', description: '3D assets for design, animation, and architecture projects.' },
    { name: 'Video Clips & Animations', description: 'Stock videos and animations for content creation.' },
  ],
},
{
  name: 'Office & Supplies',
  description: 'Office essentials, from furniture to organization tools, to keep your workspace efficient.',
  subcategories: [
    { name: 'Office Furniture', description: 'Desks, chairs, and storage solutions for a productive workspace.' },
    { name: 'Office Electronics', description: 'Essential electronics like monitors, keyboards, and more.' },
    { name: 'Printers & Scanners', description: 'High-quality printers, scanners, and multifunction devices.' },
    { name: 'Ink & Toner', description: 'Cartridges and refills for printers and copiers.' },
    { name: 'Filing & Organization', description: 'Folders, organizers, and filing systems for managing documents.' },
  ],
},
{
  name: 'Pet Supplies',
  description: 'Essential products for pet care, including food, toys, grooming, and health items for all pet types.',
  subcategories: [
    { name: 'Pet Food', description: 'Nutritious food and treats for dogs, cats, and other pets.' },
    { name: 'Pet Toys', description: 'Interactive and fun toys to keep pets entertained.' },
    { name: 'Pet Grooming', description: 'Shampoos, brushes, and grooming tools for pet care.' },
    { name: 'Pet Health & Wellness', description: 'Supplements, medicines, and health products for pets.' },
    { name: 'Aquarium Supplies', description: 'Tanks, filters, and decor for aquariums and aquatic pets.' },
  ],
},
{
  name: 'Gifts & Party Supplies',
  description: 'Find everything for celebrations, including gift wrap, decor, party favors, and more.',
  subcategories: [
    { name: 'Gift Wrapping', description: 'Gift wrap, bags, ribbons, and bows for special occasions.' },
    { name: 'Greeting Cards', description: 'Cards for birthdays, holidays, and other celebrations.' },
    { name: 'Party Decor', description: 'Decorations like banners, centerpieces, and streamers.' },
    { name: 'Balloons', description: 'Colorful balloons for parties and events.' },
    { name: 'Candles', description: 'Decorative and scented candles for celebrations or relaxation.' },
    { name: 'Party Games', description: 'Fun games and activities for parties and gatherings.' },
  ],
},
{
  name: 'Industrial & Scientific',
  description: 'Equipment, tools, and supplies for industrial, scientific, and agricultural needs.',
  subcategories: [
    { name: 'Lab Equipment', description: 'Laboratory tools and instruments for scientific research.' },
    { name: 'Industrial Tools', description: 'Heavy-duty tools for construction and industrial use.' },
    { name: 'Safety Supplies', description: 'Safety gear and protective equipment for workplace hazards.' },
    { name: 'Construction Equipment', description: 'Machinery and tools for construction and building projects.' },
  ],
},
{
  name: 'Eco-Friendly & Sustainable',
  description: 'Environmentally friendly products that promote sustainability and eco-conscious choices.',
  subcategories: [
    { name: 'Recycled Products', description: 'Products made from recycled materials to reduce waste.' },
    { name: 'Organic Food', description: 'Natural and organic food products for healthy living.' },
    { name: 'Natural Beauty Products', description: 'Eco-friendly skincare and beauty products.' },
    { name: 'Solar Products', description: 'Solar-powered devices and renewable energy solutions.' },
  ],
},
{
  name: 'Vintage & Collectibles',
  description: 'Unique and rare items, including antiques, collectibles, and memorabilia for enthusiasts and collectors.',
  subcategories: [
    { name: 'Vintage Clothing', description: 'Retro and vintage apparel from various eras.' },
    { name: 'Antiques & Furniture', description: 'Timeless antique furniture and decor items.' },
    { name: 'Collectible Toys', description: 'Rare and collectible toys for enthusiasts.' },
    { name: 'Memorabilia', description: 'Items related to famous events, people, or places.' },
    { name: 'Vinyl Records & Music Memorabilia', description: 'Classic vinyl records and music-related items.' },
    { name: 'Vintage Jewelry & Watches', description: 'Antique and vintage jewelry and timepieces.' },
    { name: 'Art & Prints', description: 'Fine art pieces, prints, and collectible artworks.' },
    { name: 'Books & Magazines', description: 'Vintage books, magazines, and rare publications.' },
  ],
},
]